<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Gear</name>
   <tag></tag>
   <elementGuidId>39b21d8c-2122-46fc-9762-d4dc32df0883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-6 > span:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-6']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot; Gear&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3f1137d-4232-454a-8f68-a1b433018a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gear</value>
      <webElementGuid>b70216bb-568a-432b-aef7-0ce21e44b2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-6&quot;)/span[2]</value>
      <webElementGuid>fa88edb7-0a86-4030-bfff-20cf8a678706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ui-id-6']/span[2]</value>
      <webElementGuid>78cf760b-65cc-4831-a4ed-7d76718ffccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shorts'])[2]/following::span[2]</value>
      <webElementGuid>ed37936f-7038-47a5-bbed-55d96aa2f5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pants'])[2]/following::span[3]</value>
      <webElementGuid>15caf9a5-5b69-4044-b6b4-cec51ec7a47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bags'])[1]/preceding::span[1]</value>
      <webElementGuid>f7564e6b-f513-4098-b0d4-a2ee71fc7c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fitness Equipment'])[1]/preceding::span[2]</value>
      <webElementGuid>6e038a1a-a9cd-4c1a-baf3-a219689ed000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gear']/parent::*</value>
      <webElementGuid>dfbb7e4c-127a-4e85-b3ee-9b1399adca59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span[2]</value>
      <webElementGuid>58506fd2-069e-4537-b748-99e4c090effe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Gear' or . = 'Gear')]</value>
      <webElementGuid>228c1e33-e468-427d-99cc-8d30c4ae28e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
