<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Best Way_ko_unique_8</name>
   <tag></tag>
   <elementGuidId>b989e599-2979-4109-9b65-96c9d4e81835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ko_unique_8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ko_unique_8&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Fixed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9e17093-1672-4fe6-9024-7102dbc49c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c32be8ea-69e6-44ef-b624-65a828f67f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d5ed29d7-ee95-4318-8502-4de667abadf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {'aria-labelledby': 'label_method_' + method.method_code + '_' + method.carrier_code + ' ' + 'label_carrier_' + method.method_code + '_' + method.carrier_code,
                    'checked': element.rates().length == 1 || element.isSelected}, value: method.carrier_code + '_' + method.method_code, checked: element.isSelected</value>
      <webElementGuid>d2a13dc6-5d86-4fc9-b9ed-fa2dd56a511e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_method_flatrate_flatrate label_carrier_flatrate_flatrate</value>
      <webElementGuid>90991326-01ae-473b-84d1-2c1a5fb9c38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>flatrate_flatrate</value>
      <webElementGuid>6fef8708-508d-497f-adb3-cb49a463ef81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ko_unique_8</value>
      <webElementGuid>7be2f7ab-21ef-4910-af64-339327b73626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-shipping-method-load&quot;)/table[@class=&quot;table-checkout-shipping-method&quot;]/tbody[1]/tr[@class=&quot;row&quot;]/td[@class=&quot;col col-method&quot;]/input[@class=&quot;radio&quot;]</value>
      <webElementGuid>71ef12a8-7908-43b5-89e2-b12272023c86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ko_unique_8']</value>
      <webElementGuid>42424480-ceac-45a8-97b9-6d5da631d960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>3d4befc4-1296-4121-be69-fa65986edf52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>f69a463a-7c85-4f9a-ad84-04057419b361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ko_unique_8']</value>
      <webElementGuid>dcea669c-b28e-4dcc-97da-ff0e56376eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
