<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//input[@id='search']//following::span[1]</description>
   <name>btnSearch</name>
   <tag></tag>
   <elementGuidId>ea077beb-0f32-4483-971f-7a2d5f1ba8b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
