<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Juno Jaket1</name>
   <tag></tag>
   <elementGuidId>2e3a92d8-192f-47fa-89cf-5dc8772f6221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qs-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='qs-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Juno Jaket&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>af4dd78e-3f03-4495-8b7d-4137052fa094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>acdb0f48-a5de-42b9-a6cc-ae8845d9635f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qs-option-0</value>
      <webElementGuid>be2afe66-05eb-4a61-adfb-69618ac84b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ee889036-cb4a-4392-a91b-7c781a040c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Juno Jaket1</value>
      <webElementGuid>82e04bae-ff11-4168-8cf7-122420d42eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qs-option-0&quot;)</value>
      <webElementGuid>cd8c2c89-340b-4dc0-978d-ec1ebc9af2a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='qs-option-0']</value>
      <webElementGuid>46b6a90f-a248-4085-9d04-d73ee98ed7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_autocomplete']/ul/li</value>
      <webElementGuid>e1d6afa2-326c-40d1-bf17-cd7ab9de9ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::li[1]</value>
      <webElementGuid>2457c642-694d-4fab-8845-d8106d4c5cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::li[1]</value>
      <webElementGuid>b53f8d7b-1d9d-4ebf-8c2e-86e6a5e53316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[1]/preceding::li[1]</value>
      <webElementGuid>dbad6548-0749-464a-acc2-11d8854e6652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li</value>
      <webElementGuid>a063f4f2-aa77-42e2-85b5-c1a91a995a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'qs-option-0' and (text() = ' Juno Jaket1' or . = ' Juno Jaket1')]</value>
      <webElementGuid>b1aa5fe3-b5ad-4b11-939e-9740b962f16a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
