<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Juno Jaket</name>
   <tag></tag>
   <elementGuidId>03d09998-3b7a-4b8c-9c2f-bd0e7621e7da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.qs-option-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='qs-option-0']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Juno Jaket&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b0e62f33-6ec1-4a4b-ab8f-7a09628f49e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qs-option-name</value>
      <webElementGuid>57968723-c6c2-42fa-8e1c-8de7cde2fe74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Juno Jaket</value>
      <webElementGuid>87ccde3d-e63e-4b84-ba8a-6c41f9c63970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qs-option-0&quot;)/span[@class=&quot;qs-option-name&quot;]</value>
      <webElementGuid>72205c97-2c23-44d9-a920-1109157f2776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='qs-option-0']/span</value>
      <webElementGuid>0eb1c8cb-e53a-4e1b-bc67-5e25fd4d2d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::span[1]</value>
      <webElementGuid>4ed187c3-c58a-41a1-8f44-a7b1dfa61c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::span[2]</value>
      <webElementGuid>31dc1b79-adaf-498c-8b0f-d148d94bdfb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[1]/preceding::span[2]</value>
      <webElementGuid>152e1891-c1c8-433a-842d-837b677e114d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[3]/preceding::span[2]</value>
      <webElementGuid>2510f094-b482-4e61-bc06-8877e680df36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Juno Jaket']/parent::*</value>
      <webElementGuid>5297018a-2371-4530-ab6b-4f2c7fa79e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li/span</value>
      <webElementGuid>1fbc5c61-0069-4a24-9c29-1e64569f9036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Juno Jaket' or . = ' Juno Jaket')]</value>
      <webElementGuid>9a42b0be-3e30-49e6-8fa9-276e25454069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
