<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UserModule</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>35cbb189-2ecd-415d-97d8-85707d22181f</testSuiteGuid>
   <testCaseLink>
      <guid>733501e6-f52e-4a9b-9c1d-9b7423a7e8c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/MSTC_01_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b86f06a6-23e6-47c0-868d-a086fd92431a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acbfe500-157f-4ed9-9983-e5ff35b5cebd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0b9c406-a3c6-412a-bd1a-d43f2aabc413</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignOn/MSTC_01_CreateAnAccount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e1b2764-c508-46f4-941e-4883f4438cd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>147cdc26-6138-4bfe-b126-0bf3d37fef02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignOn/MSTC_02_DuplicateUserValidation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79e0665b-26c1-4cc3-9cd2-922471163039</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
