<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter discount code_discount_code</name>
   <tag></tag>
   <elementGuidId>c987092a-3e7a-4d71-983b-da89f8bf3fea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#discount-code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='discount-code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter discount code&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f41a8c2-7c2d-43d1-95de-f53d8157f967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>25dd4f2e-2192-43da-86b4-188b04b43441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c627d3bc-a268-4d14-af9e-9b5de6f227ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>discount-code</value>
      <webElementGuid>64ee6225-4bcb-4443-9067-a3e8dbd252e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>discount_code</value>
      <webElementGuid>78bb86d1-973e-4a85-9538-9d13de302d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{'required-entry':true}</value>
      <webElementGuid>009243cc-cc94-4777-b6e4-3ce036f5ed27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: couponCode, attr:{disabled:isApplied() , placeholder: $t('Enter discount code')} </value>
      <webElementGuid>37ee9790-5af5-47b4-8aa2-2ecd2ba98579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter discount code</value>
      <webElementGuid>4ac44cec-4870-4f0a-bc3c-7282e401b094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discount-code&quot;)</value>
      <webElementGuid>22c40c0e-f6ff-4fa7-8025-f134bd167db3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='discount-code']</value>
      <webElementGuid>70d72c66-158e-479d-afe7-8b7dd0c822f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='discount-form']/div/div/div/input</value>
      <webElementGuid>abf40dba-dcb5-4fc7-bc39-6d4944d3f02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/input</value>
      <webElementGuid>0bb0b49b-2cf1-4f34-b040-84f1d3fb08f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'discount-code' and @name = 'discount_code' and @placeholder = 'Enter discount code']</value>
      <webElementGuid>54df2c15-03a7-4c73-8afc-0eeac64b20f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
