<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selectShippingMethod</name>
   <tag></tag>
   <elementGuidId>aeb7893c-5434-430f-9055-b0bcd4b06efa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ko_unique_2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='label_carrier_bestway_tablerate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Fixed&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42c0e53f-6db8-4eb5-a5ab-f2348b1357a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8c448727-a98e-46f6-9e56-05311a5faee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0aaf6d1a-12c4-4c07-ae59-7fc8375a7dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {'aria-labelledby': 'label_method_' + method.method_code + '_' + method.carrier_code + ' ' + 'label_carrier_' + method.method_code + '_' + method.carrier_code,
                    'checked': element.rates().length == 1 || element.isSelected}, value: method.carrier_code + '_' + method.method_code, checked: element.isSelected</value>
      <webElementGuid>e95e42dd-5171-4c84-8de2-f2e7c5e42b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_method_flatrate_flatrate label_carrier_flatrate_flatrate</value>
      <webElementGuid>8cf3dbd4-941a-408d-adb6-02cc7d087992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>flatrate_flatrate</value>
      <webElementGuid>877dbe20-3702-434c-8e67-b6b614053769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ko_unique_2</value>
      <webElementGuid>4b1d10e2-bd50-45ab-adab-ea4500ec3f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-shipping-method-load&quot;)/table[@class=&quot;table-checkout-shipping-method&quot;]/tbody[1]/tr[@class=&quot;row&quot;]/td[@class=&quot;col col-method&quot;]/input[@class=&quot;radio&quot;]</value>
      <webElementGuid>02bbade0-4658-435b-8080-4cf313cf079c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ko_unique_2']</value>
      <webElementGuid>9cbd08ec-ad59-49bd-ad62-6e73f16c507f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>6cbee470-01cb-47b8-9235-220feeaeb627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>2a423161-e67a-4dd8-9883-97ffbd4591e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ko_unique_2']</value>
      <webElementGuid>a6e107e7-cea0-4792-ad94-deb6ed225811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
