<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Apply Discount Code</name>
   <tag></tag>
   <elementGuidId>c5f52a85-a12f-4517-b634-a6d1a9b5b56b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#block-discount-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='block-discount-heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Apply Discount Code &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>80e3b642-00cb-42af-a941-b6efddc6f4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action action-toggle</value>
      <webElementGuid>ec700e9b-fb15-43f1-83ca-00f41ac01a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>block-discount-heading</value>
      <webElementGuid>a854c609-bb44-4119-92b3-d54d6032370f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>1a0c6adf-6f3c-4e19-8784-a999651b3a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>92e5693a-cb4f-44b1-84c4-100db9858876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Apply Discount Code
        </value>
      <webElementGuid>afdc33a4-63a1-49f2-ba18-ce6137af1caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-discount-heading&quot;)</value>
      <webElementGuid>55bfbc9c-0b80-4a4b-93d8-5b20c114fc71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='block-discount-heading']</value>
      <webElementGuid>94ed8d93-ff43-4639-83b8-4f449a085828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='co-payment-form']/fieldset/div[3]/div/span</value>
      <webElementGuid>4bc75cb2-d928-49eb-9077-b4eafd4e9b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Payment method available.'])[1]/following::span[1]</value>
      <webElementGuid>e17d029d-26d8-4b31-973d-1ea1f4da3a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place Order'])[1]/following::span[2]</value>
      <webElementGuid>1ce7b4c2-c08c-40fd-9206-4dc5d8227c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter discount code'])[1]/preceding::span[2]</value>
      <webElementGuid>ae5c233f-ca19-4ddd-926b-d3a7f2d53d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>45181740-749f-4323-8ecc-fc265d05af56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'block-discount-heading' and (text() = '
            Apply Discount Code
        ' or . = '
            Apply Discount Code
        ')]</value>
      <webElementGuid>5bcb82f3-786d-441a-a623-4e1d196c9f22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
