<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Compare</name>
   <tag></tag>
   <elementGuidId>ab5a9faf-17ae-4696-9a8c-c8d1313c8cf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.action.compare.primary > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div[3]/div/div[2]/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Compare&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9c450e3e-c134-48f0-b64b-52bbc57702d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compare</value>
      <webElementGuid>71d3bdf1-2e2e-494a-8c5b-ba7f1191b30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;sidebar sidebar-additional&quot;]/div[@class=&quot;block block-compare&quot;]/div[@class=&quot;block-content&quot;]/div[@class=&quot;actions-toolbar&quot;]/div[@class=&quot;primary&quot;]/a[@class=&quot;action compare primary&quot;]/span[1]</value>
      <webElementGuid>45d17d7c-804b-480c-9a78-a4e0bedb0dde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div[3]/div/div[2]/div/div/a/span</value>
      <webElementGuid>1d6e01d4-08a6-43cf-aebd-2d6cef846aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove This Item'])[2]/following::span[1]</value>
      <webElementGuid>089e6cd7-339a-4e89-84fc-8060dc1b62e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clamber Watch'])[1]/following::span[2]</value>
      <webElementGuid>96a5b465-2f43-407c-b146-6ab0bb02fab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/preceding::span[1]</value>
      <webElementGuid>3f01935a-8406-47c8-8bfb-6eb20d21965d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recently Ordered'])[1]/preceding::span[2]</value>
      <webElementGuid>069bdbbf-69a4-4112-9df8-53b301bcce26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compare']/parent::*</value>
      <webElementGuid>3cc25a88-24a1-49e3-9a25-43dad4bda18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/a/span</value>
      <webElementGuid>6d8a4c5b-b9fd-476f-baa4-f320b54b09df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Compare' or . = 'Compare')]</value>
      <webElementGuid>af82dae2-147d-45a3-886c-d09811e74afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove This Item'])[1]/following::span[1]</value>
      <webElementGuid>a8a9104a-56a7-430c-b568-9edbe4f47326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
